version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: playto_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: playto
    ports:
      - "7001:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: playto_redis
    ports:
      - "7002:6379"

volumes:
  pgdata: